const minordetails = {
    gtitle: "",
    gfirstname: "",
    gmiddleName: "",
    glastName: "",
    gdob: "",
    gpostalcode: "",
    gemail: "",
    gaddress1: "",
    gaddress2: "",
    gaddress3: "",
    gcity: "",
    gregion: "",
};

const claimantdetails = {
    title: "",
    firstname: "",
    middlename: "",
    lastname: "",
    dob: "",
    ninumber: "",
    englishlevel: "",
    mobile: "",
    landLine: "",
    email: "",
    postalcode: "",
    address1: "",
    address2: "",
    address3: "",
    city: "",
    region: "",
    scotland: "N",
    displayBasic: "false",
    minor: "",
    showMinorModal: "",
    claimantDetails: "",
    minorDetails: "",
    accidentDetails: "",
    vehiclesDetails: "",
    images: "",
    passengers: "",
    language_details: "",
    password: "",
    alternativeNumber: "",
};

const accidentdetails = {
    accdate: "",
    acctime: "",
    circumcode: "",
    circumdescr: "",
    location: "",
    description: "",
    rdweathercond: "",
    driverpassenger: "",
    injclasscode: "",
    injdescr: "",
    injlevel: "",
    injdescription: "",
    injlength: "",
    ongoing: "N",
    medicalinfo: "N",
    evidenceDetails: "",
    vehicledamage: "",
};

const vehicledetails = {
    vehiclecondition: "",
    location: "",
    reportedtopolice: "",
    reportedOn: "",
    referenceNumber: "",
    registerationno: "",
    makemodel: "",
    insurer: "",
    policyno: "",
    refno: "",
    partyregno: "",
    partymakemodel: "",
    partyinsurer: "",
    partypolicyno: "",
    partyrefno: "",
    greencardno: "",
    address1: "",
    partyname: "",
    partycontactno: "",
    partyaddress: "",
    evidenceDetails: "",
    alternativeNumber: "",
    policycover: "",
    policyholder: "",
    recovered: "",
    recoveredby: "",
    instorage: "",
    storage: "",
    lengthoflicenceheld: "",
};

export { claimantdetails, minordetails, accidentdetails, vehicledetails };
